- name: Setup Linux Workstation
  hosts: local
  vars:
    dot_repo_root: "{{ playbook_dir | dirname }}"
    can_install_packages: true
  roles:
    - { role: nvm, tags: ["nvm"]}
    - { role: packages, tags: ["packages"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: zsh, tags: ["zsh"]}
    - { role: i3, tags: ["i3"]}
    - { role: git, tags: ["git"]}


